---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## The team

The team is 


## Participants

Ann John (Corresponding author), Population Psychiatry, Suicide and Informatics, Swansea University Medical School, Swansea University, Swansea, UK; Cochrane Satellite for Suicide and Self-harm Prevention; Public Health Wales NHS Trust. A.john@swansea.ac.uk

Emily Eyles, National Institute for Health Research Applied Research Collaboration West (NIHR ARC West) at University Hospitals Bristol NHS Foundation Trust, UK. emily.eyles@bristol.ac.uk

Luke A McGuinness, Population Health Sciences, Bristol Medical School, University of Bristol, Bristol, UK. luke.mcguinness@bristol.ac.uk

Chukwudi Okolie, Population Psychiatry, Suicide and Informatics, Swansea University Medical School, Swansea University, Swansea, UK; Cochrane Satellite for Suicide and Self-harm Prevention; Public Health Wales NHS Trust. C.o.okolie@swansea.ac.uk

Babatunde K Olorisade, Population Health Sciences, Bristol Medical School, University of Bristol, Bristol, UK. b.k.olorisade@bristol.ac.uk

Lena Schmidt, Population Health Sciences, Bristol Medical School, University of Bristol, Bristol, UK. lena.schmidt@bristol.ac.uk

Roger T. Webb, NIHR Greater Manchester Patient Safety Translational Research Centre; Division of Psychology and Mental Health, The University of Manchester, Manchester Academic Health Sciences Centre, Manchester, UK. roger.webb@manchester.ac.uk  

Ella Arensman, School of Public Health and National Suicide Research Foundation, University College Cork, Cork, Ireland. earensman@ucc.ie 

Keith Hawton, Centre for Suicide Research, University Department of Psychiatry, Oxford, UK.; Oxford NHS Foundation Trust. keith.hawton@psych.ox.ac.uk 

Nav Kapur, NIHR Greater Manchester Patient Safety Translational Research Centre; Division of Psychology & Mental Health, The University of Manchester and; Greater Manchester Mental Health NHS Foundation Trust, Manchester, UK. nav.kapur@manchester.ac.uk 

Paul Moran, National Institute for Health Research Biomedical Research Centre, University Hospitals Bristol NHS Foundation Trust and University of Bristol, Bristol, UK; Population Health Sciences; Bristol Medical School; University of Bristol. paul.moran@bristol.ac.uk 

Rory C O’Connor, Suicidal Behaviour Research Lab, Institute of Health & Wellbeing, University of Glasgow. Rory.OConnor@glasgow.ac.uk 

Siobhan O’Neill, School of Psychology, Ulster University. sm.oneill@ulster.ac.uk 

Julian PT Higgins, Population Health Sciences, Bristol Medical School, University of Bristol, Bristol, UK; National Institute for Health Research Biomedical Research Centre, University Hospitals Bristol NHS Foundation Trust and University of Bristol, Bristol, UK; National Institute for Health Research Applied Research Collaboration West (NIHR ARC West) at University Hospitals Bristol NHS Foundation Trust, UK. Julian.Higgins@bristol.ac.uk

David Gunnell, National Institute for Health Research Biomedical Research Centre, University Hospitals Bristol NHS Foundation Trust and University of Bristol, Bristol, UK; Population Health Sciences; Bristol Medical School; University of Bristol. D.J.Gunnell@bristol.ac.uk

