---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# The impact of the COVID-19 pandemic on self-harm and suicidal behaviour: protocol for a living systematic review

### Abstract

__Background:__ The COVID-19 pandemic has caused widespread morbidity and mortality as well as disruption to people’s lives and livelihoods around the world; this has occurred as a result of both infection with the virus itself and the health protection measures taken to curb its spread. There are concerns that rates of suicide, suicidal behaviours and self-harm may rise during and in the aftermath of the pandemic. Given the likely rapidly expanding research evidence base on the pandemic’s impact on rates of suicide, suicidal behaviours and self-harm and emerging evidence about how best to mitigate such effects, it is important that the best available knowledge is made readily available to policymakers, public health specialists and clinicians as soon as is possible. To facilitate this, we plan to undertake a living systematic review focusing on suicide prevention in relation to COVID-19.

__Method:__ Regular automated searches will feed into a web-based screening system which will also host the data extraction form for included articles. Our eligibility criteria are wide and include aspects of incidence and prevalence of suicidal behaviour, effects of exposures and effects of interventions in relation to the COVID-19 pandemic, with minimal restrictions on the types of study design to be included. The outcomes assessed will be death by suicide; self-harm or attempted suicide (including hospital attendance and/or admission for these reasons); and suicidal thoughts/ideation. There will be no restriction on study type, except for single case reports. There will be no restriction on language of publication. The review will be updated at three-monthly intervals if a sufficient volume of new evidence justifies doing so.

__Conclusions:__ Our living review will provide a regular synthesis of the most up-to-date research evidence to guide public health and clinical policy to mitigate the impact of COVID-19 on suicide. 

